WITH dados_disciplinas (codigo, nome, carga_horaria, tipo, turno, periodo_ideal) AS (
    VALUES
        ('COMP359', 'PROGRAMAÇÃO 1', 72, 'obrigatoria'::tipo_disciplina, 'T', 1),
        ('COMP360', 'LÓGICA PARA PROGRAMAÇÃO', 72, 'obrigatoria'::tipo_disciplina, 'T', 1),
        ('COMP361', 'COMPUTAÇÃO, SOCIEDADE E ÉTICA', 72, 'obrigatoria'::tipo_disciplina, 'T', 1),
        ('COMP362', 'MATEMÁTICA DISCRETA', 72, 'obrigatoria'::tipo_disciplina, 'T', 1),
        ('COMP363', 'CÁLCULO DIFERENCIAL E INTEGRAL', 144, 'obrigatoria'::tipo_disciplina, 'T', 1),
        ('COMP364', 'ESTRUTURA DE DADOS', 72, 'obrigatoria'::tipo_disciplina, 'M', 2),
        ('COMP365', 'BANCO DE DADOS', 72, 'obrigatoria'::tipo_disciplina, 'T', 2),
        ('COMP366', 'ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES', 72, 'obrigatoria'::tipo_disciplina, 'M', 2),
        ('COMP367', 'GEOMETRIA ANALÍTICA', 72, 'obrigatoria'::tipo_disciplina, 'T', 2),
        ('COMP368', 'REDES DE COMPUTADORES', 72, 'obrigatoria'::tipo_disciplina, 'T', 3),
        ('COMP369', 'TEORIA DOS GRAFOS', 72, 'obrigatoria'::tipo_disciplina, 'T', 3),
        ('COMP370', 'PROBABILIDADE E ESTATÍSTICA', 72, 'obrigatoria'::tipo_disciplina, 'M', 3),
        ('COMP371', 'ÁLGEBRA LINEAR', 72, 'obrigatoria'::tipo_disciplina, 'M', 3),
        ('COMP372', 'PROGRAMAÇÃO 2', 72, 'obrigatoria'::tipo_disciplina, 'T', 4),
        ('COMP373', 'PROGRAMAÇÃO 3', 72, 'obrigatoria'::tipo_disciplina, 'T', 4),
        ('COMP374', 'PROJETO E ANÁLISE DE ALGORITMOS', 72, 'obrigatoria'::tipo_disciplina, 'T', 4),
        ('COMP376', 'TEORIA DA COMPUTAÇÃO', 72, 'obrigatoria'::tipo_disciplina, 'T', 4),
        ('COMP377', 'ACE 1: PROJETO I', 75, 'obrigatoria'::tipo_disciplina, 'T', 4),
        ('COMP378', 'SISTEMAS OPERACIONAIS', 72, 'obrigatoria'::tipo_disciplina, 'T', 5),
        ('COMP379', 'COMPILADORES', 72, 'obrigatoria'::tipo_disciplina, 'T', 5),
        ('COMP380', 'INTELIGÊNCIA ARTIFICIAL', 72, 'obrigatoria'::tipo_disciplina, 'T', 5),
        ('COMP381', 'COMPUTAÇÃO GRÁFICA', 72, 'obrigatoria'::tipo_disciplina, 'T', 5),
        ('COMP382', 'PROJETO E DESENVOLVIMENTO DE SISTEMAS', 288, 'obrigatoria'::tipo_disciplina, 'M', 6),
        ('COMP383', 'ACE 2: CONTINUIDADE DO PROJETO', 75, 'obrigatoria'::tipo_disciplina, 'T', 4),
        ('COMP384', 'ACE 3: PROJETO 2', 73, 'obrigatoria'::tipo_disciplina, 'T', 4),
        ('COMP385', 'ACE 5: EVENTO', 73, 'obrigatoria'::tipo_disciplina, 'M', 4),
        ('COMP386', 'METODOLOGIA DE PESQUISA E TRABALHO INDIVIDUAL', 72, 'obrigatoria'::tipo_disciplina, 'T', 7),
        ('COMP387', 'NOÇÕES DE DIREITO', 72, 'obrigatoria'::tipo_disciplina, 'T', 7),
        ('COMP389', 'CONCEITOS DE LINGUAGEM DE PROGRAMAÇÃO', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP390', 'APRENDIZAGEM DE MÁQUINA', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP391', 'SISTEMAS DIGITAIS', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP392', 'SISTEMAS DISTRIBUÍDOS', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP393', 'REDES NEURAIS E APRENDIZADO PROFUNDO', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP395', 'INTERAÇÃO HOMEM-MÁQUINA', 72, 'eletiva'::tipo_disciplina, 'M', 8),
        ('COMP396', 'PROCESSAMENTO DIGITAL DE IMAGENS', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP397', 'COMPUTAÇÃO EVOLUCIONÁRIA', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP398', 'SISTEMAS EMBARCADOS', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP399', 'GERÊNCIA DE PROJETO', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP400', 'INTELIGÊNCIA ARTIFICIAL', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP401', 'CIÊNCIA DE DADOS', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP402', 'MICROCONTROLADORES E APLICAÇÕES', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP403', 'SEGURANÇA DE SISTEMAS COMPUTACIONAIS', 72, 'eletiva'::tipo_disciplina, 'T', 8),
        ('COMP404', 'CÁLCULO 3', 72, 'eletiva'::tipo_disciplina, 'T', 8)
)
INSERT INTO disciplinas (codigo, nome, carga_horaria, tipo, turno, periodo_ideal)
SELECT
    codigo,
    nome,
    carga_horaria,
    tipo,
    turno,
    periodo_ideal
FROM dados_disciplinas
ON CONFLICT (codigo) DO UPDATE
SET
    nome = EXCLUDED.nome,
    carga_horaria = EXCLUDED.carga_horaria,
    tipo = EXCLUDED.tipo,
    turno = EXCLUDED.turno,
    periodo_ideal = EXCLUDED.periodo_ideal;